services:
    gamma_pushpin.json_event_serializer:
        class: Gamma\Pushpin\PushpinBundle\Services\Events\Json\EventSerializer
        public: false

    gamma_pushpin.json_event_parser:
        class: Gamma\Pushpin\PushpinBundle\Services\Events\Json\EventParser
        public: false

    gamma_pushpin.json_event_factory:
        class: Gamma\Pushpin\PushpinBundle\Services\Events\Json\EventFactory
        arguments:
            parser: @gamma_pushpin.json_event_parser
            serializer: @gamma_pushpin.json_event_serializer
        tags:
          -  { name: gamma_pushpin.grip_event_factory }
