parameters:
    pushpin_helper_class: Gamma\Pushpin\PushpinBundle\Services\PushpinHelper

services:
    gamma_pushpin.pushpin_helper:
        class: %pushpin_helper_class%
        calls:
            - [setPushpinControlURI, [%gamma.pushpin.control_uri%]]

    gamma_pushpin.grip.events_factory:
        class: Gamma\Pushpin\PushpinBundle\Services\GripEventsFactory

    gamma_pushpin.converter.web_socket_events:
        class: Gamma\Pushpin\PushpinBundle\Request\ParamConverter\WebSocketEventsConverter
        arguments:
            factory: @gamma_pushpin.json_event_factory
        tags:
            - { name: request.param_converter, priority: 2, converter: gamma.web_socket.events }
