parameters:
    pushpin_helper_class: Gamma\Pushpin\PushpinBundle\Services\PushpinHelper

services:
    gamma_pushpin.pushpin_helper:
        class: %pushpin_helper_class%
        calls:
            - [setPushpinControlURI, [%gamma.pushpin.control_uri%]]

    gamma_pushpin.json_event_serializer:
        class: Gamma\Pushpin\PushpinBundle\Services\Events\JsonEventSerializer
        public: false

    gamma_pushpin.json_event_parser:
        class: Gamma\Pushpin\PushpinBundle\Services\Events\JsonEventParser
        public: false

    gamma_pushpin.json_event_factory:
        class: Gamma\Pushpin\PushpinBundle\Services\Events\JsonEventFactory
        arguments:
            parser: @gamma_pushpin.json_event_parser
            serializer: @gamma_pushpin.json_event_serializer
        tags:
          -  { name: gamma_pushpin.grip_event_factory, format: json }

    gamma_pushpin.json_events_converter:
        class: Gamma\Pushpin\PushpinBundle\Request\ParamConverter\JsonEventsParamConverter
        arguments:
            factory: @gamma_pushpin.json_event_factory
